import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';

const app=readFileSync(new URL('../app/WaitlistApp.tsx',import.meta.url),'utf8');
const hardenedGrouping=readFileSync(new URL('../supabase/harden-player-grouping.sql',import.meta.url),'utf8');
const advancedCss=readFileSync(new URL('../app/advanced.css',import.meta.url),'utf8');
const iconCss=readFileSync(new URL('../app/icon-fixes.css',import.meta.url),'utf8');
const conversion=readFileSync(new URL('../supabase/fix-team-mode-conversion.sql',import.meta.url),'utf8');
const undo=readFileSync(new URL('../supabase/fix-operator-undo-safe-update.sql',import.meta.url),'utf8');
const substitute=readFileSync(new URL('../supabase/team-substitute-next-game.sql',import.meta.url),'utf8');
const courts=readFileSync(new URL('../supabase/fix-team-court-count.sql',import.meta.url),'utf8');
const modes=readFileSync(new URL('../supabase/fix-mode-switch-preserve-players.sql',import.meta.url),'utf8');
const layout=readFileSync(new URL('../app/layout.tsx',import.meta.url),'utf8');
const worker=readFileSync(new URL('../worker/index.ts',import.meta.url),'utf8');

assert.match(conversion,/\(player_no-1\)%6=0/);
assert.match(conversion,/queue_position=\(\(player_no-1\)%6\)\+1/);
assert.match(conversion,/order by case when status='current' then 0 else 1 end/);
assert.match(undo,/update public\.king_teams set name='Repair '\|\|id::text where true/);
assert.match(substitute,/team_substitutes/);
assert.match(substitute,/end_team_rotation/);
assert.match(substitute,/end_team_king_game/);
assert.match(courts,/cfg\.mode in\('teams','teams_rejoin'\)/);
assert.match(courts,/update public\.king_teams set status='waiting'/);
assert.match(courts,/perform public\.king_fill_courts\(\)/);
assert.doesNotMatch(modes,/restore_waitlist_state/);
assert.match(modes,/left join public\.king_teams t on t\.id=p\.team_id/);
assert.match(modes,/perform public\.fill_open_court_slots\(\)/);
assert.match(modes,/perform public\.save_admin_undo\('change waitlist mode'\)/);
assert.match(app,/const badge=item\.is_host\?' \(Host\)'/);
assert.match(app,/HostAppointmentModal message=\{hostAppointmentNotice\} start=\{acknowledgeHostAppointment\}/);
assert.match(app,/admin\|\|\(operator&&!own&&!player\.is_host&&Boolean\(player\.user_id\)\)/);
assert.match(app,/host&&item\.user_id!==me\?\.user_id&&!item\.is_host&&Boolean\(item\.user_id\)/);
assert.match(app,/admin&&<button className="danger" onClick=\{restrictAction\}>/);
assert.match(app,/modal-backdrop host-appointment-backdrop/);
assert.match(advancedCss,/\.host-appointment-backdrop\s*\{\s*z-index:100;/);
assert.match(app,/setOnboarding\('idle'\);setScreen\('queue'\);\s*setHostTutorialStep\(0\);setHostTutorial\(true\)/);
assert.match(app,/onboarding!==\'idle\'\|\|hostTutorial\|\|hostAppointmentNotice/);
assert.match(app,/admin\|\|host\|\|onboarding!==\'idle\'/);
assert.match(app,/setOnboarding\('idle'\);setTutorialStep\(0\);setHostTutorial\(false\)/);
assert.match(app,/function TutorialCoach.*const safeStep=Math\.max\(0,Math\.min\(step,steps\.length-1\)\)/s);
assert.match(app,/function KingTeamCard\(\{team,me,canJoin,busy,joinTeam,start,side,showStreak,operator,admin,host,/);
assert.match(app,/<KingTeamCard[^>]+admin=\{admin\} host=\{host\}/);
assert.match(app,/previous===false&&host.*setHostAppointmentNotice/s);
assert.match(app,/if\(!hostStatusReady\)\{renderedHostStatus\.current=null;return;\}/);
assert.match(app,/Location is \* REQUIRED \* to join/);
assert.match(app,/admin-tools teams-tools.*single-court-tools.*multi-court-tools/s);
assert.match(app,/admin-tools standard-tools.*single-court-tools.*multi-court-tools/s);
assert.match(advancedCss,/Final action-panel layout/);
assert.match(advancedCss,/teams-tools\.host-tools.*repeat\(4/s);
assert.match(advancedCss,/standard-tools\.host-tools.*repeat\(6/s);
assert.match(advancedCss,/multi-court-tools:not\(\.host-tools\).*--admin-action-row:2/);
assert.match(layout,/opengym-asset-recovery/);
assert.match(layout,/asset\.includes\('\/assets\/'\)/);
assert.match(worker,/Cache-Control", "no-store, no-cache, must-revalidate"/);
assert.match(app,/const MOBILE_DRAG_HOLD_MS=450/);
assert.match(app,/const MOBILE_SCROLL_CANCEL_DISTANCE=8/);
assert.match(app,/const NAME_CHARACTER_LIMIT=30/);
assert.equal((app.match(/maxLength=\{NAME_CHARACTER_LIMIT\}/g)??[]).length,6);
assert.match(app,/used>=NAME_CHARACTER_LIMIT-5/);
assert.match(app,/First and last names can each contain up to/);
assert.match(advancedCss,/\.name-limit-counter/);
assert.match(advancedCss,/@media \(max-width:520px\) \{ \.topbar\{position:relative;padding-left:0\}\.topbar>\.logo\{position:absolute;top:40px;left:0\}/);
assert.match(app,/me\.status==='rejoin'\|\|admin\|\|!config\.geofence_enabled/);
assert.doesNotMatch(app,/admin\|\|isTeamsMode\(config\.mode\)\|\|!config\.geofence_enabled/);
assert.match(app,/className="facility-heading-label"><span>Facility<\/span> <strong>\{facility\?\.name\?\?'OpenGym'\}<\/strong><button type="button" onClick=\{confirmFacilityChange\}>Change<\/button>/);
assert.match(app,/confirm:'Log out',action:logout,actionTone:'danger',actionOnLeft:true,cancelLabel:'Never mind'/);
assert.match(advancedCss,/\.facility-heading-label\{display:flex;/);
assert.match(app,/handledSwapRequestIds=useRef\(new Set<string>\(\)\)/);
assert.match(app,/find\(request=>!handledSwapRequestIds\.current\.has\(request\.id\).*handledSwapRequestIds\.current\.add\(incoming\.id\)/s);
assert.match(app,/handledGroupRequestIds=useRef\(new Set<string>\(\)\)/);
assert.match(app,/find\(request=>!handledGroupRequestIds\.current\.has\(request\.id\).*handledGroupRequestIds\.current\.add\(incoming\.id\)/s);
assert.ok(app.includes("if(/ wants to group with you\\. \\(Current game: Game \\d+\\)$/.test(notification.message))return;"));
assert.match(hardenedGrouping,/requester_size>=6/);
assert.match(hardenedGrouping,/facility_id=fid and status in\('current','waiting'\)/);
assert.match(hardenedGrouping,/A group request is already pending between these players/);
assert.match(hardenedGrouping,/court_number=null/);
assert.match(hardenedGrouping,/destination_group:=coalesce\(requester\.group_id,gen_random_uuid\(\)\)/);
assert.match(hardenedGrouping,/old_target_group:=target\.group_id/);
assert.match(hardenedGrouping,/where facility_id=fid and group_id=old_target_group/);
assert.match(hardenedGrouping,/row_number\(\) over\(order by queue_position,id\) rn/);
assert.doesNotMatch(hardenedGrouping,/case when id=target\.id then 1 else 0 end/);
assert.match(app,/The generic RPC helper refreshes before sign-out/);
assert.match(app,/await supabase\.rpc\('leave_waitlist'\)/);
assert.match(app,/Tabs share one authenticated Supabase facility session/);
assert.match(app,/if\(document\.visibilityState!=='visible'\)return/);
assert.match(app,/async function ensureFacilityContext/);
assert.match(app,/const cancelHoldOnScroll=/);
assert.doesNotMatch(app,/const scrollBeforeHold=/);
assert.match(advancedCss,/\.king-player-row:has\(\.admin-player-actions\).*touch-action:pan-y/);
assert.match(iconCss,/\.king-player-row:has\(\.admin-player-actions\).*touch-action:pan-y/);
assert.doesNotMatch(app,/â|Ã|Â|ï¿½|�/);

console.log('waitlist integrity regression checks passed');
