import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';

const app=readFileSync(new URL('../app/WaitlistApp.tsx',import.meta.url),'utf8');
const advancedCss=readFileSync(new URL('../app/advanced.css',import.meta.url),'utf8');
const iconCss=readFileSync(new URL('../app/icon-fixes.css',import.meta.url),'utf8');
const conversion=readFileSync(new URL('../supabase/fix-team-mode-conversion.sql',import.meta.url),'utf8');
const undo=readFileSync(new URL('../supabase/fix-operator-undo-safe-update.sql',import.meta.url),'utf8');
const substitute=readFileSync(new URL('../supabase/team-substitute-next-game.sql',import.meta.url),'utf8');
const courts=readFileSync(new URL('../supabase/fix-team-court-count.sql',import.meta.url),'utf8');
const modes=readFileSync(new URL('../supabase/fix-mode-switch-preserve-players.sql',import.meta.url),'utf8');

assert.match(conversion,/\(player_no-1\)%6=0/);
assert.match(conversion,/queue_position=\(\(player_no-1\)%6\)\+1/);
assert.match(conversion,/order by case when status='current' then 0 else 1 end/);
assert.match(undo,/update public\.king_teams set name='Repair '\|\|id::text where true/);
assert.match(substitute,/team_substitutes/);
assert.match(substitute,/end_team_rotation/);
assert.match(substitute,/end_team_king_game/);
assert.match(courts,/cfg\.mode in\('teams','teams_rejoin'\)/);
assert.match(courts,/update public\.king_teams set status='waiting'/);
assert.match(courts,/perform public\.king_fill_courts\(\)/);
assert.doesNotMatch(modes,/restore_waitlist_state/);
assert.match(modes,/left join public\.king_teams t on t\.id=p\.team_id/);
assert.match(modes,/perform public\.fill_open_court_slots\(\)/);
assert.match(modes,/perform public\.save_admin_undo\('change waitlist mode'\)/);
assert.match(app,/const badge=item\.is_host\?' \(Host\)'/);
assert.match(app,/HostAppointmentModal message=\{hostAppointmentNotice\} start=\{acknowledgeHostAppointment\}/);
assert.match(app,/modal-backdrop host-appointment-backdrop/);
assert.match(advancedCss,/\.host-appointment-backdrop\s*\{\s*z-index:100;/);
assert.match(app,/setOnboarding\('idle'\);setScreen\('queue'\);\s*setHostTutorialStep\(0\);setHostTutorial\(true\)/);
assert.match(app,/onboarding!==\'idle\'\|\|hostTutorial\|\|hostAppointmentNotice/);
assert.match(app,/previous===false&&host.*setHostAppointmentNotice/s);
assert.match(app,/if\(!hostStatusReady\)\{renderedHostStatus\.current=null;return;\}/);
assert.match(app,/const MOBILE_DRAG_HOLD_MS=450/);
assert.match(app,/const MOBILE_SCROLL_CANCEL_DISTANCE=8/);
assert.match(app,/const cancelHoldOnScroll=/);
assert.doesNotMatch(app,/const scrollBeforeHold=/);
assert.match(advancedCss,/\.king-player-row:has\(\.admin-player-actions\).*touch-action:pan-y/);
assert.match(iconCss,/\.king-player-row:has\(\.admin-player-actions\).*touch-action:pan-y/);
assert.doesNotMatch(app,/â|Ã|Â|ï¿½|�/);

console.log('waitlist integrity regression checks passed');
